library(tidyverse)
library(devtools)
options(stringsAsFactors = FALSE)
devtools::install_github("patelm9/mirroR")
devtools::install_github("patelm9/caterpillaR")
devtools::install_github("patelm9/somersaulteR")
devtools::install_github("patelm9/projektoR")
devtools::install_github("patelm9/projectloggeR")
devtools::install_github("patelm9/typewriteR")
devtools::install_github("patelm9/mySeagull")

source("./R/open_metamorphysis.R")
