DROP TABLE IF EXISTS MRXW_ITA;
CREATE TABLE MRXW_ITA (
    LAT	char(3) NOT NULL,
    WD	varchar(200) NOT NULL,
    CUI	char(8) NOT NULL,
    LUI	varchar(10) NOT NULL,
    SUI	varchar(10) NOT NULL
) CHARACTER SET utf8;

