DROP TABLE IF EXISTS MRXW_JPN;
CREATE TABLE MRXW_JPN (
    LAT char(3) NOT NULL,
    WD  varchar(500) NOT NULL,
    CUI char(8) NOT NULL,
    LUI varchar(10) NOT NULL,
    SUI varchar(10) NOT NULL
) CHARACTER SET utf8;

