#' @title
#' Metathesaurus Data Definitions
#'
#' @description
#'
#' @name mth_data_definition_functions
NULL

#' @title
#' List the Human Readable Names of MTH Tables
#' @seealso
#'  \code{\link[tibble]{tribble}}
#' @export
#' @importFrom tibble tribble

readable_mth_tables <-
        function() {
                tibble::tribble(
                        ~`Table Title`,~RRF,
                        'Files', 'MRFILES.RRF',
                        'Data Elements', 'MRCOLS.RRF',
                        'Documentation for Abbreviated Values', 'MRDOC.RRF',
                        'Concept Names and Sources', 'MRCONSO.RRF',
                        'Simple Concept and Atom Attributes', 'MRSAT.RRF',
                        'Definitions', 'MRDEF.RRF',
                        'Semantic Types', 'MRSTY.RRF',
                        'History', 'MRHIST.RRF',
                        'Related Concepts', 'MRREL.RRF',
                        'Computable Hierarchies', 'MRHIER.RRF',
                        'Contexts', 'MRCXT.RRF',
                        'Mappings', 'MRMAP.RRF',
                        'Simple Mappings', 'MRSMAP.RRF',
                        'Source Information', 'MRSAB.RRF',
                        'Concept Name Ranking', 'MRRANK.RRF',
                        'Ambiguous Term Identifiers', 'AMBIGLUI.RRF',
                        'Ambiguous String Identifiers', 'AMBIGSUI.RRF',
                        'NA', 'NA',
                        'Word Index', 'MRXW_BAQ.RRF, MRXW_DAN.RRF, MRXW_DUT.RRF, MRXW_ENG.RRF, MRXW_FIN.RRF, MRXW_FRE.RRF, MRXW_GER.RRF, MRXW_HEB.RRF, MRXW_HUN.RRF, MRXW_ITA.RRF, MRXW_NOR.RRF, MRXW_POR.RRF, MRXW_RUS.RRF, MRXW_SPA.RRF, MRXW_SWE.RRF',
                        'Normalized Word Index', 'MRXNW_ENG.RRF',
                        'Normalized String Index', 'MRXNS_ENG.RRF')
        }

#' @title
#' Get the definitions of the MRCONSO Table
#' @seealso
#'  \code{\link[tibble]{tribble}}
#' @export
#' @importFrom tibble tribble

mrconso_field_definitions <-
        function() {
                tibble::tribble(~Col.,~Description,
                                'CUI', 'Unique identifier for concept',
                                'LAT', 'Language of term',
                                'TS', 'Term status',
                                'LUI', 'Unique identifier for term',
                                'STT', 'String type',
                                'SUI', 'Unique identifier for string',
                                'ISPREF', 'Atom status - preferred (Y) or not (N) for this string within this concept',
                                'AUI', 'Unique identifier for atom - variable length field, 8 or 9 characters',
                                'SAUI', 'Source asserted atom identifier [optional]',
                                'SCUI', 'Source asserted concept identifier [optional]',
                                'SDUI', 'Source asserted descriptor identifier [optional]',
                                'SAB', 'Abbreviated source name (SAB). Maximum field length is 20 alphanumeric characters. Two source abbreviations are assigned:
Root Source Abbreviation (RSAB) — short form, no version information, for example, AI/RHEUM, 1993, has an RSAB of "AIR"Versioned Source Abbreviation (VSAB) — includes version information, for example, AI/RHEUM, 1993, has an VSAB of "AIR93"
Official source names, RSABs, and VSABs are included on the UMLS Source Vocabulary Documentation page.',
                                'TTY', 'Abbreviation for term type in source vocabulary, for example PN (Metathesaurus Preferred Name) or CD (Clinical Drug). Possible values are listed on the Abbreviations Used in Data Elements page.',
                                'CODE', 'Most useful source asserted identifier (if the source vocabulary has more than one identifier), or a Metathesaurus-generated source entry identifier (if the source vocabulary has none)',
                                'STR', 'String',
                                'SRL', 'Source restriction level',
                                'SUPPRESS', 'Suppressible flag. Values = O, E, Y, or NO: All obsolete content, whether they are obsolesced by the source or by NLM. These will include all atoms having obsolete TTYs, and other atoms becoming obsolete that have not acquired an obsolete TTY (e.g. RxNorm SCDs no longer associated with current drugs, LNC atoms derived from obsolete LNC concepts). E: Non-obsolete content marked suppressible by an editor. These do not have a suppressible SAB/TTY combination.Y: Non-obsolete content deemed suppressible during inversion. These can be determined by a specific SAB/TTY combination explicitly listed in MRRANK.N: None of the aboveDefault suppressibility as determined by NLM (i.e., no changes at the Suppressibility tab in MetamorphoSys) should be used by most users, but may not be suitable in some specialized applications. See the MetamorphoSys Help page for information on how to change the SAB/TTY suppressibility to suit your requirements. NLM strongly recommends that users not alter editor-assigned suppressibility, and MetamorphoSys cannot be used for this purpose.',
                                'CVF', 'Content View Flag. Bit field used to flag rows included in Content View. This field is a varchar field to maximize the number of bits available for use.')
        }


#' @title
#' Get the definitions of al the Metathesaurus Fields
#' @description
#' Sourced from \href{https://www.nlm.nih.gov/research/umls/knowledge_sources/metathesaurus/release/columns_data_elements.html}
#' @seealso
#'  \code{\link[tibble]{tribble}}
#' @export
#' @importFrom tibble tribble

mth_field_definitions <-
        function() {
                tibble::tribble(
                ~Abbreviation,~Description,~Datatype,
                'ATN', 'Attribute name', 'varchar(100)',
                'ATNL', 'Attribute name list for a source.', 'varchar(4000)',
                'ATUI', 'Unique identifier for attribute.', 'varchar(11)',
                'ATV', 'Attribute value', 'varchar(65000)',
                'AUI', 'Unique identifier for atom', 'varchar(9)',
                'AUI1', 'Unique identifier for first atom', 'varchar(9)',
                'AUI2', 'Unique identifier for second atom', 'varchar(9)',
                'AV', 'Average Length, Characters', 'numeric(5,2)',
                'BTS', 'Size in Bytes', 'integer',
                'CENC', 'Character encoding of a source as specified by IANA', 'varchar(20)',
                'CFR', 'CUI frequency for a source', 'integer',
                'CHANGEKEY', 'CONCEPTSTATUS (if history relates to a SNOMED CT concept) or DESCRIPTIONSTATUS (if history relates to a SNOMED CT atom or "description")', 'varchar(1000)',
                'CHANGETYPE', 'Source asserted code for type of change', 'varchar(1000)',
                'CHANGEVAL', 'SNOMED CT CONCEPTSTATUS or DESCRIPTIONSTATUS value after the change took place', 'varchar(1000)',
                'CLS', 'Number of columns', 'integer',
                'CODE', 'Unique Identifier or code for string in source', 'varchar(100)',
                'COL', 'Column or data element name', 'varchar(20)',
                'CUI', 'Unique identifier for concept', 'char(8)',
                'CUI1', 'Unique identifier for first concept', 'char(8)',
                'CUI2', 'Unique identifier for second concept', 'char(8)',
                'CURVER', 'Current Version flag', 'char(1)',
                'CVF', 'Content view flag', 'varchar(50)',
                'CXN', 'The context number if the atom has multiple contexts', 'integer',
                'CXTY', 'Context type for a source', 'varchar(50)',
                'DEF', 'Definition', 'varchar(16000)',
                'DES', 'Descriptive Name', 'varchar(200)',
                'DIR', 'Source asserted directionality flag', 'varchar(1)',
                'DOCKEY', 'Key to be documented', 'varchar(50)',
                'DTY', 'SQL-92 data type for this column', 'varchar(20)',
                'EXPL', 'Detailed explanation', 'varchar(1000)',
                'FIL', 'Physical FILENAME', 'varchar(50)',
                'FMT', 'Comma separated list of COL', 'varchar(300)',
                'FROMEXPR', 'The expression that a mapping is mapped from', 'varchar(4000)',
                'FROMID', 'Metathesaurus identifier for the entity being mapped from', 'varchar(50)',
                'FROMRES', 'Restriction applicable to the entity being mapped from', 'varchar(4000)',
                'FROMRULE', 'Machine processible rule applicable to the entity being mapped from', 'varchar(4000)',
                'FROMSID', 'Source asserted identifier for the entity being mapped from', 'varchar(50)',
                'FROMTYPE', 'The type of expression that a mapping is mapped from', 'varchar(50)',
                'HCD', 'Source asserted hierarchical number or code of context member (if it exists)', 'varchar(100)',
                'IMETA', 'Version of the Metathesaurus that a source was added', 'varchar(10)',
                'ISPREF', 'Indicates whether AUI is preferred', 'char(1)',
                'LAT', 'Language of Term(s)', 'char(3)',
                'LUI', 'Unique identifier for term', 'varchar(10)',
                'MAPATN', 'Mapping attribute name (for future use)', 'varchar(20)',
                'MAPATV', 'Mapping attribute value (for future use)', 'varchar(4000)',
                'MAPID', 'Metathesaurus asserted identifier for mapping', 'varchar(50)',
                'MAPIN', 'Mapping in current subset', 'char(1)',
                'MAPRANK', 'Order in which mappings in a subset should be applied', 'integer',
                'MAPREASON', 'Reason for mapping', 'varchar(4000)',
                'MAPRES', 'Restriction applicable to this mapping', 'varchar(4000)',
                'MAPRULE', 'Machine processible rule applicable to this mapping', 'varchar(4000)',
                'MAPSETCUI', 'CUI of the map set', 'char(8)',
                'MAPSETSAB', 'SAB of the map set', 'varchar(40)',
                'MAPSID', 'Source asserted identifier for mapping', 'varchar(50)',
                'MAPSUBSETID', 'Map subset identifier used to identify a subset of related mappings within a map set', 'varchar(10)',
                'MAPTYPE', 'Type of mapping', 'varchar(50)',
                'MAX', 'Maximum Length', 'integer',
                'METAUI', 'Metathesaurus asserted unique identifier', 'varchar(50)',
                'MIN', 'Minimum Length', 'integer',
                'NSTR', 'Normalized string', 'varchar(3000)',
                'NWD', 'Normalized word', 'varchar(100)',
                'PAUI', 'Unique identifier for parent atom', 'varchar(9)',
                'PCUI', 'Concept unique identifier in the previous Metathesaurus', 'char(8)',
                'PLUI', 'Lexical unique identifier in the previous Metathesaurus', 'varchar(10)',
                'PSTR', 'Preferred name in the previous Metathesaurus', 'varchar(3000)',
                'PSUI', 'String unique identifier in the previous Metathesaurus', 'varchar(10)',
                'PTR', 'Path to root', 'varchar(1000)',
                'RANK', 'Termgroup ranking', 'integer',
                'RCUI', 'Unique identifier for root SRC concept', 'char(8)',
                'REASON', 'Explanation of change, if present', 'varchar(1000)',
                'REF', 'Documentation Section Number', 'varchar(20)',
                'REL', 'Relationship label', 'varchar(4)',
                'RELA', 'Additional relationship label', 'varchar(100)',
                'RG', 'Relationship group', 'varchar(10)',
                'RMETA', 'Version of the Metathesaurus where a version is removed', 'varchar(10)',
                'RSAB', 'Root source abbreviation', 'varchar(40)',
                'RUI', 'Unique identifier for relationship', 'varchar(10)',
                'RWS', 'Number of rows', 'integer',
                'SAB', 'Source abbreviation', 'varchar(40)',
                'SABIN', 'Source in current subset', 'char(1)',
                'SATUI', 'Source asserted attribute identifier', 'varchar(50)',
                'SAUI', 'Source asserted atom identifier', 'varchar(50)',
                'SCC', 'Content contact info for a source', 'varchar(1000)',
                'SCIT', 'Source citation', 'varchar(4000)',
                'SCUI', 'Source asserted concept identifier', 'varchar(50)',
                'SDUI', 'Source asserted descriptor identifier', 'varchar(50)',
                'SF', 'Source Family', 'varchar(40)',
                'SL', 'Source of relationship labels', 'varchar(40)',
                'SLC', 'License contact info for a source', 'varchar(1000)',
                'SON', 'Source Official Name', 'varchar(3000)',
                'SOURCEUI', 'Source asserted unique identifier', 'varchar(50)',
                'SRL', 'Source Restriction Level', 'integerinteger',
                'SRUI', 'Source attributed relationship identifier', 'varchar(50)',
                'SSN', 'Source short name', 'varchar(3000)',
                'STN', 'Semantic type tree number', 'varchar(100)',
                'STR', 'String', 'varchar(3000)',
                'STT', 'String type', 'varchar(3)',
                'STY', 'Semantic type', 'varchar(50)',
                'STYPE', 'The name of the column in MRCONSO.RRF or MRREL.RRF that contains the identifier to which the attribute is attached', 'varchar(50)',
                'STYPE1', 'The name of the column in MRCONSO.RRF that contains the first identifier to which the relationship is attached', 'varchar(50)',
                'STYPE2', 'The name of the column in MRCONSO.RRF that contains the second identifier to which the relationship is attached', 'varchar(50)',
                'SUI', 'Unique identifier for string', 'varchar(10)',
                'SUPPRESS', 'Suppressible flag', 'char(1)',
                'SVER', 'Release date or version number of a source', 'varchar(20)',
                'TFR', 'Term frequency for a source', 'integer',
                'TOEXPR', 'The expression that a mapping is mapped to', 'varchar(4000)',
                'TOID', 'Metathesaurus identifier for the entity being mapped to', 'varchar(50)',
                'TORES', 'Restriction applicable to the entity being mapped to', 'varchar(4000)',
                'TORULE', 'Machine processible rule applicable to the entity being mapped to', 'varchar(4000)',
                'TOSID', 'Source asserted identifier for the entity being mapped to', 'varchar(50)',
                'TOTYPE', 'The type of expression that a mapping is mapped to', 'varchar(50)',
                'TS', 'Term status', 'char(1)',
                'TTY', 'Term type in source', 'varchar(20)',
                'TTYL', 'Term type list for a source', 'varchar(400)',
                'TUI', 'Unique identifier of Semantic type', 'char(4)',
                'TYPE', 'Type of information', 'varchar(50)',
                'VALUE', 'Value', 'varchar(200)',
                'VCUI', 'Unique identifier for versioned SRC concept', 'char(8)',
                'VEND', 'Valid end date for a source', 'char(8)',
                'VER', 'Last release version in which CUI1 was valid', 'varchar(10)',
                'VSAB', 'Versioned source abbreviation', 'varchar(40)',
                'VSTART', 'Valid start date for a source', 'char(8)',
                'WD', 'Word in lower-case', 'varchar(500)'
                )
        }

#' @title
#' Map all the MTH Fields to the Table
#'  \code{\link[tibble]{tribble}}
#' @export
#' @importFrom tibble tribble

mth_fields_to_tables <-
        function() {
                tibble::tribble(
                ~Abbreviation,~Table,
                'ATN', 'MRSAT',
                'ATNL', 'MRSAB',
                'ATUI', 'MRSTY',
                'ATUI', 'MRSAT',
                'ATUI', 'MRDEF',
                'ATV', 'MRSAT',
                'AUI', 'MRHIER',
                'AUI', 'MRDEF',
                'AUI', 'MRCONSO',
                'AUI1', 'MRREL',
                'AUI1', 'MRAUI',
                'AUI2', 'MRREL',
                'AUI2', 'MRAUI',
                'AV', 'MRCOLS',
                'BTS', 'MRFILES',
                'CENC', 'MRSAB',
                'CFR', 'MRSAB',
                'CHANGEKEY', 'MRHIST',
                'CHANGETYPE', 'MRHIST',
                'CHANGEVAL', 'MRHIST',
                'CLS', 'MRFILES',
                'CODE', 'MRSAT',
                'CODE', 'MRCONSO',
                'COL', 'MRCOLS',
                'CUI', 'MRHIST',
                'CUI', 'AMBIGLUI',
                'CUI', 'AMBIGSUI',
                'CUI', 'CHANGE/MERGEDCUI',
                'CUI', 'MRCONSO',
                'CUI', 'MRDEF',
                'CUI', 'MRHIER',
                'CUI', 'MRSAT',
                'CUI', 'MRSTY',
                'CUI', 'MRXNS_ENG',
                'CUI', 'MRXNW_ENG',
                'CUI', 'MRXW_BAQ',
                'CUI', 'MRXW_CHI',
                'CUI', 'MRXW_CZE',
                'CUI', 'MRXW_DAN',
                'CUI', 'MRXW_DUT',
                'CUI', 'MRXW_ENG',
                'CUI', 'MRXW_EST',
                'CUI', 'MRXW_FIN',
                'CUI', 'MRXW_FRE',
                'CUI', 'MRXW_GER',
                'CUI', 'MRXW_GRE',
                'CUI', 'MRXW_HEB',
                'CUI', 'MRXW_HUN',
                'CUI', 'MRXW_ITA',
                'CUI', 'MRXW_JPN',
                'CUI', 'MRXW_KOR',
                'CUI', 'MRXW_LAV',
                'CUI', 'MRXW_NOR',
                'CUI', 'MRXW_POL',
                'CUI', 'MRXW_POR',
                'CUI', 'MRXW_RUS',
                'CUI', 'MRXW_SCR',
                'CUI', 'MRXW_SPA',
                'CUI', 'MRXW_SWE',
                'CUI', 'MRXW_TUR',
                'CUI1', 'MRAUI',
                'CUI1', 'MRCUI',
                'CUI1', 'MRREL',
                'CUI2', 'MRCUI',
                'CUI2', 'MRAUI',
                'CUI2', 'MRREL',
                'CURVER', 'MRSAB',
                'CVF', 'MRHIST',
                'CVF', 'MRMAP',
                'CVF', 'MRSMAP',
                'CVF', 'MRDEF',
                'CVF', 'MRHIER',
                'CVF', 'MRSAT',
                'CVF', 'MRREL',
                'CVF', 'MRCONSO',
                'CVF', 'MRSTY',
                'CXN', 'MRHIER',
                'CXTY', 'MRSAB',
                'DEF', 'MRDEF',
                'DES', 'MRCOLS',
                'DES', 'MRFILES',
                'DIR', 'MRREL',
                'DOCKEY', 'MRDOC',
                'DTY', 'MRCOLS',
                'EXPL', 'MRDOC',
                'FIL', 'MRCOLS',
                'FIL', 'MRFILES',
                'FMT', 'MRFILES',
                'FROMEXPR', 'MRSMAP',
                'FROMEXPR', 'MRMAP',
                'FROMID', 'MRMAP',
                'FROMRES', 'MRMAP',
                'FROMRULE', 'MRMAP',
                'FROMSID', 'MRMAP',
                'FROMTYPE', 'MRSMAP',
                'FROMTYPE', 'MRMAP',
                'HCD', 'MRHIER',
                'IMETA', 'MRSAB',
                'ISPREF', 'MRCONSO',
                'LAT', 'MRSAB',
                'LAT', 'CHANGE/DELETEDSUI',
                'LAT', 'MRCONSO',
                'LAT', 'MRXNS_ENG',
                'LAT', 'MRXNW_ENG',
                'LAT', 'MRXW_BAQ',
                'LAT', 'MRXW_CHI',
                'LAT', 'MRXW_CZE',
                'LAT', 'MRXW_DAN',
                'LAT', 'MRXW_DUT',
                'LAT', 'MRXW_ENG',
                'LAT', 'MRXW_EST',
                'LAT', 'MRXW_FIN',
                'LAT', 'MRXW_FRE',
                'LAT', 'MRXW_GER',
                'LAT', 'MRXW_GRE',
                'LAT', 'MRXW_HEB',
                'LAT', 'MRXW_HUN',
                'LAT', 'MRXW_ITA',
                'LAT', 'MRXW_JPN',
                'LAT', 'MRXW_KOR',
                'LAT', 'MRXW_LAV',
                'LAT', 'MRXW_NOR',
                'LAT', 'MRXW_POL',
                'LAT', 'MRXW_POR',
                'LAT', 'MRXW_RUS',
                'LAT', 'MRXW_SCR',
                'LAT', 'MRXW_SPA',
                'LAT', 'MRXW_SWE',
                'LAT', 'MRXW_TUR',
                'LUI', 'MRSAT',
                'LUI', 'MRXW_BAQ',
                'LUI', 'MRXW_DAN',
                'LUI', 'MRXW_FIN',
                'LUI', 'MRXW_HEB',
                'LUI', 'MRXW_LAV',
                'LUI', 'MRXW_JPN',
                'LUI', 'MRXW_SCR',
                'LUI', 'AMBIGLUI',
                'LUI', 'MRXW_POL',
                'LUI', 'MRXW_SWE',
                'LUI', 'MRXW_CZE',
                'LUI', 'MRCONSO',
                'LUI', 'MRXW_GER',
                'LUI', 'MRXW_SPA',
                'LUI', 'MRXW_ENG',
                'LUI', 'MRXNW_ENG',
                'LUI', 'MRXNS_ENG',
                'LUI', 'MRXW_DUT',
                'LUI', 'MRXW_POR',
                'LUI', 'MRXW_ITA',
                'LUI', 'MRXW_FRE',
                'LUI', 'MRXW_RUS',
                'LUI', 'CHANGE/MERGEDLUI',
                'LUI', 'MRXW_KOR',
                'LUI', 'MRXW_NOR',
                'LUI', 'MRXW_HUN',
                'LUI', 'MRXW_CHI',
                'LUI', 'MRXW_EST',
                'LUI', 'MRXW_GRE',
                'LUI', 'MRXW_TUR',
                'MAPATN', 'MRMAP',
                'MAPATV', 'MRMAP',
                'MAPID', 'MRSMAP',
                'MAPID', 'MRMAP',
                'MAPIN', 'MRCUI',
                'MAPIN', 'MRAUI',
                'MAPRANK', 'MRMAP',
                'MAPREASON', 'MRCUI',
                'MAPREASON', 'MRAUI',
                'MAPRES', 'MRMAP',
                'MAPRULE', 'MRMAP',
                'MAPSETCUI', 'MRMAP',
                'MAPSETCUI', 'MRSMAP',
                'MAPSETSAB', 'MRSMAP',
                'MAPSETSAB', 'MRMAP',
                'MAPSID', 'MRSMAP',
                'MAPSID', 'MRMAP',
                'MAPSUBSETID', 'MRMAP',
                'MAPTYPE', 'MRMAP',
                'MAX', 'MRCOLS',
                'METAUI', 'MRSAT',
                'MIN', 'MRCOLS',
                'NSTR', 'MRXNS_ENG',
                'NWD', 'MRXNW_ENG',
                'PAUI', 'MRHIER',
                'PCUI', 'CHANGE/DELETEDCUI',
                'PCUI', 'CHANGE/MERGEDCUI',
                'PLUI', 'CHANGE/DELETEDLUI',
                'PLUI', 'CHANGE/MERGEDLUI',
                'PSTR', 'CHANGE/DELETEDSUI',
                'PSTR', 'CHANGE/DELETEDLUI',
                'PSTR', 'CHANGE/DELETEDCUI',
                'PSUI', 'CHANGE/DELETEDSUI',
                'PTR', 'MRHIER',
                'RANK', 'MRRANK',
                'RCUI', 'MRSAB',
                'REASON', 'MRHIST',
                'REF', 'MRCOLS',
                'REL', 'MRAUI',
                'REL', 'MRMAP',
                'REL', 'MRSMAP',
                'REL', 'MRCUI',
                'REL', 'MRREL',
                'RELA', 'MRAUI',
                'RELA', 'MRCUI',
                'RELA', 'MRSMAP',
                'RELA', 'MRHIER',
                'RELA', 'MRREL',
                'RELA', 'MRMAP',
                'RG', 'MRREL',
                'RMETA', 'MRSAB',
                'RSAB', 'MRSAB',
                'RUI', 'MRREL',
                'RWS', 'MRFILES',
                'SAB', 'MRHIST',
                'SAB', 'MRDEF',
                'SAB', 'MRREL',
                'SAB', 'MRRANK',
                'SAB', 'MRCONSO',
                'SAB', 'MRSAT',
                'SAB', 'MRHIER',
                'SABIN', 'MRSAB',
                'SATUI', 'MRDEF',
                'SATUI', 'MRSAT',
                'SAUI', 'MRCONSO',
                'SCC', 'MRSAB',
                'SCIT', 'MRSAB',
                'SCUI', 'MRCONSO',
                'SDUI', 'MRCONSO',
                'SF', 'MRSAB',
                'SL', 'MRREL',
                'SLC', 'MRSAB',
                'SON', 'MRSAB',
                'SOURCEUI', 'MRHIST',
                'SRL', 'MRCONSO',
                'SRL', 'MRSAB',
                'SRUI', 'MRREL',
                'SSN', 'MRSAB',
                'STN', 'MRSTY',
                'STR', 'MRCONSO',
                'STT', 'MRCONSO',
                'STY', 'MRSTY',
                'STYPE', 'MRSAT',
                'STYPE1', 'MRREL',
                'STYPE2', 'MRREL',
                'SUI', 'MRSAT',
                'SUI', 'MRXW_BAQ',
                'SUI', 'MRXW_DAN',
                'SUI', 'MRXW_FIN',
                'SUI', 'MRXW_HEB',
                'SUI', 'AMBIGSUI',
                'SUI', 'MRXW_JPN',
                'SUI', 'MRXW_SWE',
                'SUI', 'MRXW_GER',
                'SUI', 'MRXW_SPA',
                'SUI', 'MRXW_DUT',
                'SUI', 'MRCONSO',
                'SUI', 'MRXNS_ENG',
                'SUI', 'MRXW_ENG',
                'SUI', 'MRXNW_ENG',
                'SUI', 'MRXW_POR',
                'SUI', 'MRXW_ITA',
                'SUI', 'MRXW_RUS',
                'SUI', 'MRXW_FRE',
                'SUI', 'MRXW_CZE',
                'SUI', 'MRXW_NOR',
                'SUI', 'MRXW_HUN',
                'SUI', 'MRXW_CHI',
                'SUI', 'MRXW_EST',
                'SUI', 'MRXW_GRE',
                'SUI', 'MRXW_KOR',
                'SUI', 'MRXW_LAV',
                'SUI', 'MRXW_POL',
                'SUI', 'MRXW_SCR',
                'SUI', 'MRXW_TUR',
                'SUPPRESS', 'MRCONSO',
                'SUPPRESS', 'MRDEF',
                'SUPPRESS', 'MRRANK',
                'SUPPRESS', 'MRREL',
                'SUPPRESS', 'MRSAT',
                'SVER', 'MRHIST',
                'SVER', 'MRSAB',
                'TFR', 'MRSAB',
                'TOEXPR', 'MRMAP',
                'TOEXPR', 'MRSMAP',
                'TOID', 'MRMAP',
                'TORES', 'MRMAP',
                'TORULE', 'MRMAP',
                'TOSID', 'MRMAP',
                'TOTYPE', 'MRMAP',
                'TOTYPE', 'MRSMAP',
                'TS', 'MRCONSO',
                'TTY', 'MRCONSO',
                'TTY', 'MRRANK',
                'TTYL', 'MRSAB',
                'TUI', 'MRSTY',
                'TYPE', 'MRDOC',
                'VALUE', 'MRDOC',
                'VCUI', 'MRSAB',
                'VEND', 'MRSAB',
                'VER', 'MRAUI',
                'VER', 'MRCUI',
                'VSAB', 'MRSAB',
                'VSTART', 'MRSAB',
                'WD', 'MRXW_FIN',
                'WD', 'MRXW_KOR',
                'WD', 'MRXW_CHI',
                'WD', 'MRXW_EST',
                'WD', 'MRXW_TUR',
                'WD', 'MRXW_POR',
                'WD', 'MRXW_ITA',
                'WD', 'MRXW_ENG',
                'WD', 'MRXW_HEB',
                'WD', 'MRXW_FRE',
                'WD', 'MRXW_DAN',
                'WD', 'MRXW_SPA',
                'WD', 'MRXW_GRE',
                'WD', 'MRXW_RUS',
                'WD', 'MRXW_BAQ',
                'WD', 'MRXW_LAV',
                'WD', 'MRXW_CZE',
                'WD', 'MRXW_HUN',
                'WD', 'MRXW_DUT',
                'WD', 'MRXW_GER',
                'WD', 'MRXW_SCR',
                'WD', 'MRXW_POL',
                'WD', 'MRXW_JPN',
                'WD', 'MRXW_NOR',
                'WD', 'MRXW_SWE')
        }


